### ISSUE TITLE
Do not call read-only collections immutable

### ISSUE THREAD

**Issue by ilya-g** [kohesive/klutter#36]
"Immutable" means that collection won't change its contents by any means. Current implementation allows them to be changed when the delegate's content changes. 
Therefore the implementations provide true read-only view of delegate collections, so I propose to call them read-only:
- `ReadOnlyList`,
- `ReadOnlySet`,
- etc

**Comment by apatrida** [comment]
They are already `ReadOnly` so it is odd to call `list.asReadOnly()` because people might think "it is already read only"

So I agree, but not sure the right naming.

If I have `toImmutable()` then that would copy the list then make it readonly which is in effect immutable because there is no way to change it without some evil reflection trick to get to the delegated list.

with `asProtected()` or `asReadOnly()` or `asFenced()` or `asWriteBlocked()` or `asRealReadOnly()` they have the issue you describe.  

So need other naming ideas for the method calls, the classes I can easily rename to `ProtectedReadOnly*`

**Comment by apatrida** [comment]
So the change log for `1.20.0` would be:
- BREAKING CHANGE:  from 1.19.x renamed `asImmutable()` to `asReadOnly()`
- BREAKING CHANGE:  from 1.19.x renamed `Immutable*` collection wrappers to `ReadOnly*`

**Comment by apatrida** [comment]
Not sure I should make:
- For collections added extensions `toImmutable()` which makes a copy first then protects the items from change by wrapping with `ReadOnly*` wrappers.  Only cruel reflection tricks can break them.

**Comment by apatrida** [comment]
maybe `toImmutable()` for list would be:

```
@Suppress("UNCHECKED_CAST")
fun <T> List<T>.toImmutable(): List<T> {
    val copy = when (this) {
        is ArrayList -> this.clone() as ArrayList<T>
        else -> this.toList()
    }
    return when (this) {
        is RandomAccess ->  ReadOnlyRandomAccessList(copy)
        else -> ReadOnlyList(copy)
    }
}
```

```
@Test fun testImmutableListCannotBeModifiedFromOriginalList() {
        val l = mutableListOf(1, 2, 3)
        val i = l.toImmutable()
        val r = l.asReadOnly()

        l.add(4)
        l.remove(element = 1)

        assertEquals(listOf(2,3,4), l) // original list changed
        assertEquals(listOf(1,2,3).asReadOnly(), i)
        assertEquals(listOf(2,3,4), r) // read only was modified by changing original
    }
```

**Comment by ilya-g** [comment]
> They are already ReadOnly so it is odd to call list.asReadOnly() because people might think "it is already read only"

`asReadOnly` could also be invoked on mutable lists.

> ```
> @Suppress("UNCHECKED_CAST")
> fun <T> List<T>.toImmutable(): List<T> {
>     val copy = when (this) {
>         is ArrayList -> this.clone() as ArrayList<T>
>         else -> this.toList()
>     }
>     return when (this) {
>         is RandomAccess ->  ReadOnlyRandomAccessList(copy)
>         else -> ReadOnlyList(copy)
>     }
> }
> ```

There is no need to preserve `RandomAccess`-ness of the original list, as the copy always support random access. Therefore it's an equivalent of `toList().asReadOnly()`, it is short and I'm not sure it benefits to be shortened to `toImmutable`.

**Comment by apatrida** [comment]
@ilya-g someone requested that the `RandomAccess` marker interface be maintained because their code does different things depending on the list type they have.  So they didn't want those optimizations to be broken.

**Comment by apatrida** [comment]
Also I think the `clone()` of array list is a lot faster than `toList()` so the specialization in `toImmutable()` is worth it.  And some people might not think to `toList()` a list to copy it.

**Comment by ilya-g** [comment]
I think `clone` and `ArrayList` copy constructor taking another `ArrayList` perform more or less the same — both involve copying elements array with `Array.copyOf`.

**Comment by ilya-g** [comment]
>  So they didn't want those optimizations to be broken.

Those optimizations depend on the internal structure of data in a list. The `RandomAccess` interface exposed is an indicator of that internal structure. 

When you create a wrapper, a view, the underlying structure of list remains the same, so there is a point in preserving the value of the indicator. When you create a copy — that copy is backed by `ArrayList` and it's always `RandomAccess`, and there is no point in pretending it doesn't support `RandomAccess`.

**Comment by apatrida** [comment]
Yes, the last is a bug, it should be if the copy is random access then to keep the flag.  

```
@Suppress("UNCHECKED_CAST")
fun <T> List<T>.toImmutable(): List<T> {
    val copy = when (this) {
        is RandomAccess -> ArrayList<T>(this)
        else -> this.toList()
    }
    return when (copy) {
        is RandomAccess ->  ReadOnlyRandomAccessList(copy)
        else -> ReadOnlyList(copy)
    }
}
```

is better.

**Comment by apatrida** [comment]
Is it better to convert to array then to array list via copy constructor, or to add to the array list in the other form with toList or neither?  (not knowing the source collection type)

**Comment by apatrida** [comment]
Unless I get rid of `toList()` I want to keep the `is RandomAccess` because I don't know `toList()` wont change internal list type one day.

**Comment by apatrida** [comment]
I'm assuming some day that `toList()` might retain collection type of original, so linked stays linked.  If not, then just make everything array list always is ok

**Comment by ilya-g** [comment]
> Unless I get rid of toList() I want to keep the is RandomAccess because I don't know toList() wont change internal list type one day.

That's wise. And that is what `asReadOnly` function do, isn't it?

**Comment by apatrida** [comment]
yep. 

these changes are in `1.20.1` releasing now
