### ISSUE TITLE
artifacts broken?

### ISSUE THREAD

**Issue by sreich** [kohesive/klutter#37]
both links on the readme, one is a 404 the other doesn't have anything within it. can't get artifacts to resolve and mvnrepository isn't showing any 2.0 versions...are there artifacts?

**Comment by apatrida** [comment]
2.x changes to different group prefix, I'll check README:

view them at
https://mvnrepository.com/artifact/uy.kohesive.klutter

**Comment by apatrida** [comment]
readme updated, thanks for reporting this.
